---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: reddit-sentiment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: wait-for-zookeeper
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z zookeeper-service 2181; do echo waiting for zookeeper; sleep 2; done;']
      - name: setup-kafka-dirs
        image: busybox:1.35
        command: 
        - sh
        - -c
        - |
          mkdir -p /var/lib/kafka/data/kafka-logs
          chown -R 1000:1000 /var/lib/kafka/data/kafka-logs
          chmod -R 755 /var/lib/kafka/data/kafka-logs
        volumeMounts:
        - name: kafka-storage
          mountPath: /var/lib/kafka/data
        securityContext:
          runAsUser: 0
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.9.1
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-service:2181"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka:9092"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_LOG_DIRS
          value: "/var/lib/kafka/data/kafka-logs"
        - name: KAFKA_LOG_RETENTION_HOURS
          value: "168"
        volumeMounts:
        - name: kafka-storage
          mountPath: /var/lib/kafka/data
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "600m"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
      volumes:
      - name: kafka-storage
        persistentVolumeClaim:
          claimName: kafka-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: reddit-sentiment
spec:
  selector:
    app: kafka
  ports:
  - port: 9092
    targetPort: 9092
  type: ClusterIP