---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer-v2
  namespace: reddit-sentiment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer-v2
  template:
    metadata:
      labels:
        app: kafka-producer-v2
    spec:
      initContainers:
      - name: wait-for-kafka
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z kafka-service 9092; do echo waiting for kafka; sleep 2; done;']
      containers:
      - name: kafka-producer
        image: sudarsan222/kafka_producer:v3
        env:
        - name: BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: KAFKA_BOOTSTRAP_SERVERS  
          value: "kafka:9092"
        - name: BOOTSTRAP
          value: "kafka:9092"
        - name: STARTUP_DELAY
          value: "5"
        - name: INPUT
          value: "/app/data/Reddit_datasetv1.txt"  # Fixed path
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ps aux | grep python || echo 'producer not running'"
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 5

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-producer-v2-service
  namespace: reddit-sentiment
spec:
  selector:
    app: kafka-producer-v2
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP